SCAL-74116-docs-deployment-on-github-pages
ts-blink/embed-sdk pull request #14
Opened 2021-01-27 12:53 UTC by pankajp-ts

Ticket - https://thoughtspot.atlassian.net/browse/SCAL-74116

- did GitHub pages setup on repo
- `gh-pages` branch got created `please do not delete that branch`
- added deployment script

2021-01-28 09:14 UTC, ayonghosh requested changes
Let's set it up such that we can deploy Github pages from any Git branch

2021-02-02 07:49 UTC, ayonghosh requested changes

2021-02-02 07:49 UTC, ayonghosh commented on package.json
> +        "publish-docs": "gh-pages -d public -b 7.3.0-docs",
We need to parameterise the branch name. We can't hardcode 7.3.0-docs as there could be many branches in future.

2021-02-02 07:49 UTC, ayonghosh commented on gatsby-config.js
> +    pathPrefix: '/embed-sdk',
Do we really need the pathPrefix?

2021-02-02 07:50 UTC, pankajp-ts commented on gatsby-config.js
> +    pathPrefix: '/embed-sdk',
yes it's needed since this is a organization and we have multiple repos in it

2021-02-02 11:57 UTC, ayonghosh commented on scripts/gatsby-commands.js
> +                return '7.3.0-docs';
Let's not use any default value. Tell the user than a branch name needs to be specified explicitly.

2021-02-02 11:57 UTC, ayonghosh reviewed
LGTM after addressing comment

2021-02-02 12:23 UTC, pankajp-ts commented on scripts/gatsby-commands.js
> +                return '7.3.0-docs';
but same branch needs to be set in settings as well, so this is two way process.

2021-02-02 12:23 UTC, pankajp-ts commented on scripts/gatsby-commands.js
> +                return '7.3.0-docs';
also whatever branch name you will specify here will loose all the files and folder except what is generated by build inside public folder

2021-02-02 13:19 UTC, merged