SCAL-76071-style-developer-documentation
ts-blink/embed-sdk pull request #21
Opened 2021-02-05 11:23 UTC by harsh-ts

Ticket - https://thoughtspot.atlassian.net/browse/SCAL-76071

2021-02-08 07:02 UTC, ayonghosh commented on docs/src/components/Document/index.tsx
> +            dangerouslySetInnerHTML={{
Are we expecting HTML content to be injected here, or just plaintext?

2021-02-08 07:02 UTC, ayonghosh commented on docs/src/components/Header/index.scss
> +    z-index: 99;
Let's use a variable for the z-indices

2021-02-08 07:03 UTC, ayonghosh commented on docs/src/components/LeftSidebar/data.ts
> +export default [
What is this for? Navigation? Shouldn't that come from the asciidoc content directly?

2021-02-08 07:04 UTC, ayonghosh commented on docs/src/components/Search/index.scss
> +@import '../../assets/styles/variables.scss';
Can we try and see if we can use

2021-02-08 07:05 UTC, ayonghosh commented on docs/src/pages/404.tsx
> +const pageStyles = {
Can we put these in CSS?

2021-02-08 07:07 UTC, ayonghosh requested changes
Please post some screenshots so we can see how these changes look like visually

2021-02-08 07:09 UTC, pankajp-ts commented on docs/src/components/LeftSidebar/data.ts
> +export default [
@ayonghosh we can skip this for now, I'm working on nav.adoc file integration, will remove this file in my PR.

2021-02-08 07:59 UTC, harsh-ts commented on docs/src/components/Document/index.tsx
> +            dangerouslySetInnerHTML={{
We are expecting HTML content coming from graphql query and it will get injected here

2021-02-08 08:06 UTC, harsh-ts commented on docs/src/components/Header/index.scss
> +    z-index: 99;
Will do the needful

2021-02-08 08:07 UTC, harsh-ts commented on docs/src/components/LeftSidebar/data.ts
> +export default [
This just static data for now in order to do some styling for the left nav bar will remove this in future

2021-02-08 08:18 UTC, harsh-ts commented on docs/src/components/Search/index.scss
> +@import '../../assets/styles/variables.scss';
Sorry I didn't get your comment, as we are using `$lightgrey` variable here that's why we imported variables.scss

2021-02-08 08:18 UTC, harsh-ts commented on docs/src/pages/404.tsx
> +const pageStyles = {
Will do the needful

2021-02-08 10:44 UTC, harsh-ts commented
Here is SS 

![image](https://user-images.githubusercontent.com/78337774/107209320-a5555080-6a28-11eb-9ab4-8221e679a331.png)

2021-02-09 07:00 UTC, ayonghosh commented on docs/src/assets/styles/index.scss
> +/*active class without background*/
**end** active class without background

2021-02-09 07:01 UTC, ayonghosh commented on docs/src/components/LeftSidebar/data.ts
> +export default [
Let's add a TODO in the code then

2021-02-09 07:01 UTC, ayonghosh reviewed
Minor comments. LGTM otherwise.

2021-02-09 07:44 UTC, pankajp-ts commented
> Minor comments. LGTM otherwise.

@ayonghosh can you please approve as well?

2021-02-09 08:05 UTC, ayonghosh approved these changes
LGTM

2021-02-09 08:05 UTC, merged