Scal 77089 css changes
ts-blink/embed-sdk pull request #30
Opened 2021-02-12 06:18 UTC by harsh-ts

Ticket link - https://thoughtspot.atlassian.net/browse/SCAL-77089
This PR contains:
- Fixed CSS for left bar panel.
- Added styling for scrollbar

2021-02-12 08:18 UTC, ashubham requested changes

2021-02-12 08:18 UTC, ashubham commented on docs/src/pages/index.tsx
> +        }
Whats going on here ? can we explain via comments.

2021-02-12 08:18 UTC, ashubham commented on docs/src/components/LeftSidebar/index.scss
> +                        font-weight: 300 !important;
we should avoid !important

2021-02-12 10:18 UTC, pankajp-ts commented on docs/src/components/LeftSidebar/index.scss
> +                        font-weight: 300 !important;
I merged harsh PR (https://github.com/ts-blink/embed-sdk/pull/30) to unblock myself, I'll share it with him.

2021-02-12 10:25 UTC, pankajp-ts commented on docs/src/pages/index.tsx
> +        }
edges comes from graphql query which basically contains adoc docs translations
then we fetch edge index for requested pageid and later get title & html
if we won't find any edge we show 404 page
we pass html to passThrouhHandler along with query params which return html with dynamically replaces values like 'tshost'
since navigation always rendered on the left we do the same thing but separately

2021-02-12 10:26 UTC, pankajp-ts commented on docs/src/pages/index.tsx
> +        }
I'll add comments in my PR

2021-02-12 10:39 UTC, pankajp-ts commented on docs/src/pages/index.tsx
> +        }
updated in my PR - https://github.com/ts-blink/embed-sdk/pull/31

2021-02-12 15:43 UTC, harsh-ts commented on docs/src/components/LeftSidebar/index.scss
> +                        font-weight: 300 !important;
Yes. I've removed it.

2021-02-12 16:41 UTC, ayonghosh commented on docs/src/assets/styles/index.scss
> +    src: url('../fonts/Plain-Medium.otf') format('opentype');
Do we want to add ttf, woff and woff2 as well? How's the browser support for opentype?

2021-02-12 16:41 UTC, ayonghosh commented on docs/src/assets/styles/index.scss
> +// Scrollbar styling start
Use /* */ style comments

2021-02-12 16:41 UTC, ayonghosh commented on docs/src/assets/styles/index.scss
> +// Scrollbar styling end
Same here

2021-02-12 16:43 UTC, ayonghosh approved these changes
LGTM after addressing comments

2021-02-15 04:07 UTC, harsh-ts commented on docs/src/assets/styles/index.scss
> +    src: url('../fonts/Plain-Medium.otf') format('opentype');
To support the font for the old browser(Which doesn't support OpenType)

2021-02-15 04:07 UTC, harsh-ts commented on docs/src/assets/styles/index.scss
> +// Scrollbar styling start
Will do the needful

2021-02-15 04:07 UTC, harsh-ts commented on docs/src/assets/styles/index.scss
> +// Scrollbar styling end
Will do the needful

2021-02-15 07:30 UTC, merged