[SCAL-77546] - Added left nav resizable functionality
ts-blink/embed-sdk pull request #65
Opened 2021-02-24 08:26 UTC by harsh-ts

This PR contains:

- Left nav resizable functionality.

Here is a demo:

https://user-images.githubusercontent.com/78337774/108967126-1d687b00-76a5-11eb-9c82-f8de22d9bb47.mp4

2021-02-25 09:36 UTC, ayonghosh requested changes

2021-02-25 09:36 UTC, ayonghosh commented on package.json
> +    "dependencies": {
Let's move these to devDependencies. We don't want to install these when someone wants to install the SDK

2021-02-25 13:19 UTC, harsh-ts commented on package.json
> +    "dependencies": {
Sure I will make the changes

2021-03-01 06:30 UTC, ayonghosh approved these changes

2021-03-01 06:34 UTC, merged