Tse docs draft2
ts-blink/embed-sdk pull request #66
Opened 2021-02-25 05:23 UTC by ShashiSubramanya

- Added link attributes to resolve the link issues raised via SCAL-78089 and  SCAL-78018
- Minor edits to SDK files (fixed typos)
- updates to SAML SSO and Security settings pages
- Updated links in all other pages to include the "Window=_blank" attribute.

2021-02-25 07:25 UTC, pankajp-ts requested changes
After addressing comments we can merge PR

2021-02-25 07:25 UTC, pankajp-ts commented on docs/src/asciidocs/common/nav.adoc
> +** link:{{tshost}}/#/everywhere/playground/search[Playground]
Please add `window=_parent` to avoid nested iframe

2021-02-25 07:25 UTC, pankajp-ts commented on docs/src/asciidocs/sdk-reference.adoc
> + <a href="{{tshost}}/#/everywhere/playground/search" id="preview-in-playground">Preview in Playground</a>
Please add `window=_parent` to avoid nested iframe

2021-02-25 07:25 UTC, pankajp-ts commented on docs/src/asciidocs/spotdev-portal.adoc
>  <a href="{{tshost}}/#/everywhere/playground/search" id="preview-in-playground">Visit Playground</a>
Please add `window=_parent` to avoid nested iframe
please add it for all preview buttons

2021-02-25 13:38 UTC, ShashiSubramanya commented on docs/src/asciidocs/spotdev-portal.adoc
>  <a href="{{tshost}}/#/everywhere/playground/search" id="preview-in-playground">Visit Playground</a>
The link attribute (target="_parent") for playground links and buttons is added.

2021-02-25 13:39 UTC, ShashiSubramanya commented on docs/src/asciidocs/common/nav.adoc
> +** link:{{tshost}}/#/everywhere/playground/search[Playground]
The link attribute (target="_parent") for playground links and buttons is added.

2021-02-26 05:09 UTC, pankajp-ts approved these changes
LGTM 👍

2021-02-26 05:09 UTC, merged