[SCAL - 77544]: Add copy button on code blocks
ts-blink/embed-sdk pull request #67
Opened 2021-02-26 05:58 UTC by harsh-ts

Ticket link -> https://thoughtspot.atlassian.net/browse/SCAL-77701, https://thoughtspot.atlassian.net/browse/SCAL-77544

This PR contains:

- Copy button displayed on code blocks.
- Copy to clipboard functionality.
- Tooltip display on copy button click.
- Code highlighting.

Here is a demo of changes:
https://user-images.githubusercontent.com/78337774/109261235-8d9e0a80-7825-11eb-8658-eeedb6c2927c.mp4

2021-02-26 07:19 UTC, pankajp-ts requested changes

2021-02-26 07:19 UTC, pankajp-ts commented on docs/src/assets/styles/highlight.scss
> +        color: #000080;
color should come from a common file i.e. variable.scss

2021-02-26 07:19 UTC, pankajp-ts commented on docs/src/components/Document/index.scss
> +@import '../../assets//styles/highlight.scss';
`assets//styles` remove extra `/`

2021-02-26 07:57 UTC, harsh-ts commented on docs/src/assets/styles/highlight.scss
> +        color: #000080;
Okay I'll do that.

2021-02-26 07:58 UTC, harsh-ts commented on docs/src/components/Document/index.scss
> +@import '../../assets//styles/highlight.scss';
I'll fix that.

2021-03-01 06:20 UTC, ayonghosh commented on docs/src/assets/svg/copy.svg
> +<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
Can you run this through https://jakearchibald.github.io/svgomg/ so we get rid of redundant stuff

2021-03-01 06:21 UTC, ayonghosh commented on docs/src/components/Document/helper.ts
> +export const addEventListner = (element: HTMLElement, ...args: HTMLElement[]) => {
Typo in Listener

2021-03-01 06:22 UTC, ayonghosh commented on docs/src/components/Document/helper.ts
> +import hljs from "highlight.js"
Use single quotes for consistency

2021-03-01 06:22 UTC, ayonghosh commented on docs/src/components/Document/helper.ts
> +        document.execCommand("copy");
Use single quotes

2021-03-01 06:24 UTC, ayonghosh commented on docs/src/components/Document/helper.ts
> +    document.querySelectorAll("pre code").forEach(block => {
Use single quotes

2021-03-01 06:28 UTC, ayonghosh commented on docs/src/components/Document/helper.ts
> +export const customizeDocContent = () => {
Possible to use event delegation here?

2021-03-01 10:55 UTC, harsh-ts commented on docs/src/assets/svg/copy.svg
> +<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
Sure. Looks useful!

2021-03-01 10:56 UTC, harsh-ts commented on docs/src/components/Document/helper.ts
> +export const addEventListner = (element: HTMLElement, ...args: HTMLElement[]) => {
Yeah. Thanks for pointing this out.

2021-03-01 10:59 UTC, harsh-ts commented on docs/src/components/Document/helper.ts
> +        document.execCommand("copy");
Okay

2021-03-01 10:59 UTC, harsh-ts commented on docs/src/components/Document/helper.ts
> +    document.querySelectorAll("pre code").forEach(block => {
Yeah sure

2021-03-01 11:02 UTC, harsh-ts commented on docs/src/components/Document/helper.ts
> +export const customizeDocContent = () => {
Using event delegation will be expensive.

2021-03-01 11:02 UTC, harsh-ts commented on docs/src/components/Document/helper.ts
> +import hljs from "highlight.js"
Yes it is a npm module but it's used this way.

2021-03-03 09:55 UTC, ayonghosh approved these changes

2021-03-03 11:28 UTC, merged